{% set name = "mord" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b60002734e33ca7fad9f94999c70b27fe038eb069cbd0fb08d6027c3d34a7bb3

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - mord

about:
  home: https://pypi.python.org/pypi/mord
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Ordinal regression models
  doc_url: https://pythonhosted.org/mord/
  dev_url: http://github.com/fabianp/mord

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
